### PR TITLE
Write a blog post about the motivations of GesaltJS

### PR DESCRIPTION
**Pull request by pepicrft**
I wrote up a blog post about the motivations behind building Gestalt. I'm curious to know from you if there's another motivation that you think should be core to the project.

You can preview the blog post here: https://deploy-preview-12--gestalt-docs.netlify.app/blog/2022/01/19/why-gestalt

### CODE REVIEW

**Comment by josemasar** [comment]
In summary: I´ve just read the article and I think it summarizes well our initial interests to build this framework. We can expect that when our code evolves, we might see other strengths in the framework to be highlighted. 

 Suggestions:

- Make in bold "take inspiration from the pool of fantastic community web frameworks" at the end of the article to emphasize that we will use the best-in-class tools. This also gives recognition to everyone who has already built a fantastic tool. 

- I believe mentioning "Capitalism" in an article to convience people to join the community may generate friction as it can be considered something political. I think stating "as an open-source framework that’s community-driven and free of business interests" is sufficient to clarify and spread the message. 

- I wouldn´t hesitate to say that you are doing mentorship with programmers with less experience than you. This might be appreciated by people who wants to become a mentor or people needs one.

**Review by josemasar — APPROVED** [review]

**Comment by pepicrft** [comment]
Thanks for the comments @josemasar. I 100% agree with your points. I went ahead and applied your suggestions.

**Comment by pepicrft** [comment]
@rbarbadillo / @lascenify I'm curious to hear your thoughts on the ideas.

**Comment by rbarbadillo** [comment]
I have few amendments to suggest. On the technical side, I am still developing a taste for web frameworks but the described approach makes a lot of sense to me. I particularly liked the sentence expressing the "opinionated by default but still flexible" way.
On the values side, I just finished (and really liked) reading the DHH article shared a couple of days ago and it reminded me of it. Just for the sake of being nit-picky with the phrasing, I'd change the second sentence of the paragraph to:
>We strongly believe in it as a beautiful altruistic activity, a space for people to share their ideas with others and create a foundation for other ideas to be built upon.

**Review by rbarbadillo — APPROVED** [review]

**Comment by pepicrft** [comment]
> I have few amendments to suggest. On the technical side, I am still developing a taste for web frameworks but the described approach makes a lot of sense to me. I particularly liked the sentence expressing the "opinionated by default but still flexible" way.

The way I've seen other frameworks and tools putting it is something along the lines of:

> Make the easy things easy, and everything else possible.

We make things easy by providing default and opinions, and everything else possible by providing APIs to change or extend those opinions. If the default is to configure everything yourself it can feel very overwhelming for someone using the framework for the first time.

> On the values side, I just finished (and really liked) reading the DHH article shared a couple of days ago and it reminded me of it.

Liked it too. Have you seen some polemic that emerged after? Some people think he forgot to mention that the framework got financial support through companies like GitHub and Shopify that put resources to work full time on the framework.

> I'd change the second sentence of the paragraph to:

I applied your suggestions and pushed a new commit 🚀

**Pull request merged**
